### ISSUE TITLE
getting started + submission

### ISSUE THREAD

**Issue by cameronjacoby** [sf-wdi-24/rails-for-zombies#1]
Can you add the instructions to fork / cone (getting started) and submit a PR (submission)? I think it would also help to have a couple questions for them to answer rather than just having them write what they learned. It's a little too vague as is.

**Comment by ben-manning** [comment]
Hey, I've got some questions up and a more detailed manner for submission.  Let me know if I need to add more to it.

**Comment by cameronjacoby** [comment]
@ben-manning This is perfect - thanks so much for adding those! :+1:
